# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'sinatra'
gem 'activerecord', '~>4.2.6'
gem 'rake'
gem 'sqlite3'

group :test do
  gem 'pry'
  gem 'minitest'
  gem 'rack-test'
end
